feat: clean up backend and dockerfiles

diff --git a/container/Dockerfile.backend b/container/Dockerfile.backend
--- a/container/Dockerfile.backend
+++ b/container/Dockerfile.backend
@@ -5,9 +5,10 @@ ARG IMAGE_FROM=$GB_IMAGE_FROM
 FROM $IMAGE_FROM as goblet-setup
 WORKDIR /goblet/app
 ENV GB_SUB_REPO=backend
-COPY container/scripts/docker/be.entrypoint.sh /entrypoint.sh
-COPY .nvmrc .nvmrc 
+COPY .nvmrc .nvmrc
+COPY .yarnrc .yarnrc
 
+# Install deps
 RUN <<EOF
   set -eux;
 
@@ -16,29 +17,9 @@ RUN <<EOF
 
   # Preinstall any dependecies for settting up the image
   apt-get update && apt-get install --yes --no-install-recommends \
-    gpg \
     curl \
-    nano \
-    docker \
-    iptables \
     openssh-client \
-    ca-certificates \
-    debian-keyring \
-    apt-transport-https \
-    debian-archive-keyring
-
-  # Install Node.js and yarn
-  NODE_VER=$(cat ./.nvmrc | cut -d "." -f 1)
-  curl -sL https://deb.nodesource.com/setup_${NODE_VER:-16}.x | bash -
-  apt-get install -y nodejs
-  npm install -g yarn
-  yarn global add turbo
-
-  # Download kubectl
-  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-  chmod +x kubectl
-  mkdir -p ~/.local/bin
-  mv ./kubectl ~/.local/bin/kubectl
+    ca-certificates
 
   rm -rf /var/lib/apt/lists/*
   rm -rf /var/lib/apt/lists.d/*
@@ -46,15 +27,66 @@ RUN <<EOF
   apt-get clean
   apt-get autoclean
 
-  chmod a+x /entrypoint.sh
 EOF
 
+# Install setup node + yarn
+RUN <<EOF
+  set -eux;
+
+  # Install Node.js and yarn
+  NODE_VER=$(cat ./.nvmrc | cut -d "." -f 1)
+  curl -sL https://deb.nodesource.com/setup_${NODE_VER:-16}.x | bash -
+  apt-get install -y nodejs
+  npm install -g yarn
+  yarn global add turbo dot-json
+
+EOF
 # ---- End Stage ---- #
 
 # ---- Prune Stage ---- #
 FROM goblet-setup as goblet-pruner
 WORKDIR /goblet/app
 COPY . .
+# Clean up repo for backend
+RUN <<EOF
+  set -eux;
+
+  rm -rf /goblet/app/repos/dind
+  rm -rf /goblet/app/repos/screencast
+  rm -rf /goblet/app/repos/testUtils
+
+  cd /goblet/app/repos/backend
+  yarn json:rm
+
+  cd /goblet/app/repos/conductor
+  yarn json:rm
+
+  cd /goblet/app/repos/shared
+  yarn json:rm
+
+  cd /goblet/app/repos/workflows
+  yarn json:rm
+
+  cd /goblet/app
+  yarn json:rm
+
+  dot-json package.json devDependencies -d
+  dot-json package.json resolutions.@jest/transform -d
+  dot-json package.json resolutions.@jest/create-cache-key-function -d
+  dot-json package.json resolutions.@keg-hub/args-parse -d
+  dot-json package.json resolutions.@keg-hub/ask-it -d
+  dot-json package.json resolutions.@keg-hub/spawn-cmd -d
+  dot-json package.json resolutions.@monaco-editor/react -d
+  dot-json package.json resolutions.expect -d
+  dot-json package.json resolutions.jest -d
+  dot-json package.json resolutions.jest-jasmine2 -d
+  dot-json package.json resolutions.playwright -d
+  dot-json package.json resolutions.nodemon -d
+  dot-json package.json resolutions.ts-jest -d
+  dot-json package.json resolutions.typescript -d
+
+EOF
+
 RUN turbo prune --docker --scope=@gobletqa/backend
 COPY ./configs ./out/full/configs
 COPY ./gobletRoot.js ./out/full/gobletRoot.js
@@ -66,10 +98,10 @@ FROM goblet-setup as goblet-installer
 WORKDIR /goblet/app
 COPY --from=goblet-pruner /goblet/app/out/json/ .
 COPY --from=goblet-pruner /goblet/app/out/yarn.lock ./yarn.lock
-RUN yarn install
-# ---- End Stage ---- #
+RUN yarn install --production
+# # ---- End Stage ---- #
 
-# ---- Build Stage ---- #
+# # ---- Build Stage ---- #
 FROM goblet-setup as goblet-builder
 WORKDIR /goblet/app
 COPY --from=goblet-pruner /goblet/app/out/full/ .
@@ -92,7 +124,10 @@ RUN <<EOF
   cp -R /goblet/app/repos/backend/dist/pullImages.ts /goblet-runner/repos/backend/scripts/pullImages.ts
   cp -R /goblet/app/repos/backend/dist/goblet.default.config.js /goblet-runner/configs/goblet.default.config.js
 EOF
-# ---- End Stage ---- #
+# # ---- End Stage ---- #
+
+
+FROM bitnami/kubectl:latest as kubectl
 
 # ---- Run Stage ---- #
 FROM goblet-setup as goblet-runner
@@ -121,10 +156,10 @@ ENV HOME=/root \
     PATH=$PATH:/usr/local/share/.config/yarn/global/node_modules/.bin
 
 COPY --from=goblet-builder /goblet-runner /goblet/app
+COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/bin/
 
 WORKDIR /goblet/app/repos/backend
 EXPOSE $GB_BE_PORT
 EXPOSE $GB_NO_VNC_PORT
 
-ENTRYPOINT ["/entrypoint.sh"]
 CMD [ "yarn", "serve" ]
